name: Test electron-chrome-extensions

on:
  push:
    paths:
    - 'packages/**'
  pull_request:
    paths:
    - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Setup dependencies
      run: |
        npm run boot-ci

    - name: Build
      run: |
        npm run build

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          npm run test
