name: Test electron-chrome-extensions

on:
  push:
    paths:
    - 'packages/**'
    - '.github/workflows/*.yml'
  pull_request:
    paths:
    - 'packages/**'
    - '.github/workflows/*.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    # continue-on-error: true
    name: Test electron@${{ matrix.electron_ver}} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        arch: [amd64] # pointless now
        # electron_ver: ["^16.0.0", "^17.0.0", "^18.0.0", "^19.0.0", "^20.0.0", "^21.0.0"]
        electron_ver: ["^16.0.0", "^17.0.0", "^18.0.0", "^19.0.0", "^20.0.0"]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Setup dependencies
      run: |
        npm run boot-ci
      env:
        ELECTRON_VER: ${{ matrix.electron_ver }}

    - name: Build
      run: |
        npm run build

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          npm run test
