name: Test electron-chrome-extensions

on:
  push:
    paths:
    - 'packages/**'
    - '.github/workflows/*.yml'
  pull_request:
    paths:
    - 'packages/**'
    - '.github/workflows/*.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        arch: [amd64] # pointless now

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Setup dependencies
      run: |
        npm run boot-ci

    - name: Build
      run: |
        npm run build

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          npm run test
